// Generated by scripts/import-work.mjs — do not edit by hand.
// Rerun: npm run import -- <folder>

import type { ImportedProject } from "./projects";

export const IMPORTED: Record<string, ImportedProject[]> = {
  directing: [],
  photography: [],
  videography: [],
  production: [],
};
